
[[snippets]]
prefix = "regex_pk"
body = '''r"^$1(?P<${2:pk}>\d+)/$"'''
detail = '''r"^(?P<pk>\d+)/$"'''

[[snippets]]
prefix = "regex_slug"
body = '''r"^$1(?P<${2:slug}>[-\w]+)/$"'''
detail = '''r"^(?P<slug>[-\w]+)/$"'''

[[snippets]]
prefix = "path_str"
body = "<str:$1>"

[[snippets]]
prefix = "path_int"
body = "<int:$1>"

[[snippets]]
prefix = "path_slug"
body = "<slug:$1>"

[[snippets]]
prefix = "path_uuid"
body = "<uuid:$1>"

[[snippets]]
prefix = "path_path"
body = "<path:$1>"
