
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-10-31T12:30:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e8f1fa1b2426236fe6fa7e05076947732916cf2",
 "version": "5.0.0a7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
