#!/usr/bin/env bash
# set-layout - set custom monitor layout with xrandr based on connected outputs

if type xrandr &>/dev/null; then 
    outputs=$(xrandr | grep -i connected | grep -v discon | cut -f1 -d' ' | tr '\n' ',' | sed 's/,$/\n/')

    case "$outputs" in 
        DP-1,HDMI-1)
            xrandr \
            --output HDMI-1 --mode 1920x1080 --pos 2560x0 --rotate right \
            --output DP-1 --primary --mode 2560x1440 --pos 0x240 --rotate normal \
            --output DP-2 --off --output DP-3 --off --output DVI-D-1 --off
            echo "Monitor layout set to 2560x1440 (horizontal) ^ 1920x1080 (vert)"
            ;;
        DP-1)
            xrandr \
            --output DP-1 --primary --mode 2560x1440 --pos 0x240 --rotate normal \
            --output HDMI-1 --off --output DP-2 --off --output DP-3 --off --output DVI-D-1 --off
            echo "Monitor layout set to 2560x1440 (horizontal)"
            ;;
        HDMI-1)
            xrandr \
            --output HDMI-1 --mode 1920x1080 --pos 2560x0 --rotate right \
            --output DP-1 --off --output DP-2 --off --output DP-3 --off --output DVI-D-1 --off
            echo "Monitor layout set to 1920x1080 (vert)"
            ;;
        *)
            echo "No monitor setup found for the outputs $outputs";;
    esac
fi
