#!/usr/bin/bash

temp=$(mktemp -d)

main() {
  local dir=${1-"$HOME/.folws-dotfiles"}
  if [[ -d "$dir" ]]; then
    echo "You already have the dotfiles installed in $dir you nonce!"
    exit 1
  fi

  pushd $temp >/dev/null
  curl -s -L https://github.com/folws/dotfiles/archive/master.tar.gz | tar -xvz -C $temp

  mv $temp/* $dir

  ./$dir/install --all -v --skip-select
}

cleanup() {
  rm -rf $temp
  exit
}

trap cleanup INT
trap cleanup SIGHUP
trap cleanup SIGINT
trap cleanup SIGTERM

main "$@"
