config:
  dotpath: home
  backup: true
  create: true
  banner: true
  keepdot: false
  showdiff: true
  link_dotfile_default: link
  link_on_import: link
actions:
  confirm: read {0} "[y/N]" -n 1 -r [[ $REPLY =~ ^[Yy]$ ]] && {1}
dotfiles:
  d_nvim:
    dst: ~/.config/nvim/
    src: config/nvim
    link: link_children
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: link_children
  d_wallpapers:
    src: ../wallpapers
    dst: ~/.wallpapers
    link: link_children
  d_x:
    src: config/x
    dst: ~/.config/x
    link: link_children
  d_sh:
    src: config/sh
    dst: ~/.config/sh
    link: link_children
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
    link: link_children
  d_spicetify:
    src: config/spicetify
    dst: ~/.config/spicetify
    link: link_children
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link_children
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link_children
  d_picom:
    src: config/picom
    dst: ~/.config/picom
    link: link_children
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link_children
  d_fish_shell:
    src: config/fish
    dst: ~/.config/fish
    link: link_children
  d_fish_shell_omf:
    src: config/omf
    dst: ~/.config/omf
    link: link_children
  d_flashfocus:
    src: config/flashfocus
    dst: ~/.config/flashfocus
    link: link_children
  d_firefox_themes:
    src: config/firefox/
    dst: ~/.mozilla/firefox/themes
    link: link_children
  d_kitty:
    src: config/kitty/
    dst: ~/.config/kitty
    link: link_children
  f_firefox_tabpage:
    src: bin/run-tabpage
    dst: ~/bin/run-tabpage
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_pywal_rofi_colorscheme:
    src: config/wal/colorschemes/dark/default.rasi
    dst: ~/.config/wal/colorschemes/dark/default.rasi
  f_pywal_rofi_template:
    src: config/wal/templates/colors-rofi-dark.rasi
    dst: ~/.config/wal/templates/colors-rofi-dark.rasi
  f_pywal_xresources_template:
    src: config/wal/templates/colors.Xresources
    dst: ~/.config/wal/templates/colors.Xresources
    actions:
    - confirm "Symlink generated pywal Xresources?" "ln -s {{@@ _dotfile_abs_dst @@}}
      ~/.Xresources"
  f_deskopen:
    src: bin/deskopen
    dst: ~/bin/deskopen
  f_figlet-test:
    src: bin/figlet-test
    dst: ~/bin/figlet-test
  f_rofi_launcher:
    src: bin/app-launcher
    dst: ~/bin/app-launcher
  f_laun.ch:
    src: bin/laun.sh
    dst: ~/bin/laun.sh
  f_powermenu:
    src: bin/powermenu
    dst: ~/bin/powermenu
  f_lockscreen:
    src: bin/lockscreen
    dst: ~/bin/lockscreen
  f_ls-chars:
    src: bin/ls-chars
    dst: ~/bin/ls-chars
  f_post-hibernate:
    src: bin/post-hibernate.sh
    dst: ~/bin/post-hibernate.sh
  f_scr:
    src: bin/scr
    dst: ~/bin/scr
  f_swal:
    src: bin/swal
    dst: ~/bin/swal
  f_lch:
    src: bin/lch
    dst: ~/bin/lch
  f_fishy:
    src: dotfiles/root/bin/fishy
    dst: /usr/bin/fishy
    chmod: '755'
  f_kautostart.sh:
    src: bin/kautostart.sh
    dst: ~/bin/kautostart.sh
    chmod: '755'
profiles:
  bin:
    dotfiles:
    - f_lch
    - f_laun.ch
    - f_scr
  wallpapers:
    dotfiles:
    - d_wallpapers
  firefox:
    dotfiles:
    - d_firefox_themes
    - f_firefox_tabpage
  fish_shell:
    dotfiles:
    - d_fish_shell
    - d_fish_shell_omf
  rofi:
    dotfiles:
    - d_rofi
    - f_rofi_launcher
    - f_pywal_rofi_template
    - f_pywal_rofi_colorscheme
  neovim:
    dotfiles:
    - d_nvim
  kitty:
    dotfiles:
    - d_kitty
  _base:
    dotfiles:
    - f_gitconfig
    - d_sh
    - d_x
    include:
    - bin
    - neovim
    - wallpapers
    - firefox
    - fish_shell
  i3:
    dotfiles:
    - d_i3
    - d_polybar
    - d_picom
    - d_flashfocus
    - d_dunst
    - f_swal
    - f_scr
    - f_pywal_xresources_template
    - f_post-hibernate
    - f_ls-chars
    - f_lockscreen
    - f_powermenu
    include:
    - _base
    - rofi

  spaceship:
    include:
    - _base
    - kitty
  4tlas:
    include:
    - i3
    - kitty
  rhea:
    dotfiles:
    - f_fishy
    - f_kautostart.sh
