actions:
  confirm: read {0}"[y/N]" -n 1 -r
    [[ $REPLY =~ ^[Yy]$ ]] && {1}
config:
  dotpath: user
  backup: true
  create: true
  banner: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  d_nvim:
    dst: ~/.config/nvim/
    src: config/nvim
    link: link_children
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: link_children
  d_wallpapers:
    src: ../wallpapers
    dst: ~/.wallpapers
    link: link_children
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_profile:
    src: profile
    dst: ~/.profile
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
    link: link_children
  d_spicetify:
    src: config/spicetify
    dst: ~/.config/spicetify
    link: link_children
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link_children
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link_children
  d_picom:
    src: config/picom
    dst: ~/.config/picom
    link: link_children
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link_children
  d_fish_shell:
    src: config/fish
    dst: ~/.config/fish
    link: link_children
  d_fish_shell_omf:
    src: config/omf
    dst: ~/.config/omf
    link: link_children
  d_flashfocus:
    src: config/flashfocus
    dst: ~/.config/flashfocus
    link: link_children
  d_firefox_themes:
    src: config/firefox/
    dst: ~/.mozilla/firefox/themes
    link: link_children
  f_firefox_tabpage:
    src: local/bin/run-tabpage
    dst: ~/.local/bin/run-tabpage
  f_kitty_conf:
    src: config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  f_pywal_rofi_colorscheme:
    src: config/wal/colorschemes/dark/default.rasi
    dst: ~/.config/wal/colorschemes/dark/default.rasi
  f_pywal_rofi_template:
    src: config/wal/templates/colors-rofi-dark.rasi
    dst: ~/.config/wal/templates/colors-rofi-dark.rasi
  f_pywal_xresources_template:
    src: config/wal/templates/colors.Xresources
    dst: ~/.config/wal/templates/colors.Xresources
    actions:
      - confirm "Symlink generated pywal Xresources?" "ln -s {{@@ _dotfile_abs_dst @@}} ~/.Xresources"
  f_deskopen:
    src: local/bin/deskopen
    dst: ~/.local/bin/deskopen
  f_figlet-test:
    src: local/bin/figlet-test
    dst: ~/.local/bin/figlet-test
  f_rofi_launcher:
    src: local/bin/app-launcher
    dst: ~/.local/bin/app-launcher
  f_launch-singleton:
    src: local/bin/launch-singleton
    dst: ~/.local/bin/launch-singleton
  f_powermenu:
    src: local/bin/powermenu
    dst: ~/.local/bin/powermenu
  f_lockscreen:
    src: local/bin/lockscreen
    dst: ~/.local/bin/lockscreen
  f_ls-chars:
    src: local/bin/ls-chars
    dst: ~/.local/bin/ls-chars
  f_post-hibernate:
    src: local/bin/post-hibernate.sh
    dst: ~/.local/bin/post-hibernate.sh
  f_scr:
    src: local/bin/scr
    dst: ~/.local/bin/scr
  f_swal:
    src: local/bin/swal
    dst: ~/.local/bin/swal
profiles:
  wallpapers:
    dotfiles:
      - d_wallpapers
  firefox:
    dotfiles:
      - d_firefox_themes
      - f_firefox_tabpage
  fish_shell:
    dotfiles:
      - d_fish_shell
      - d_fish_shell_omf
  rofi:
    dotfiles:
      - d_rofi
      - f_rofi_launcher
      - f_pywal_rofi_template
      - f_pywal_rofi_colorscheme
  neovim:
    dotfiles:
      - d_nvim
  _base:
    dotfiles:
      - f_gitconfig
    include:
      - neovim
      - wallpapers
      - firefox
      - fish_shell
  i3:
    dotfiles:
      - d_i3
      - d_polybar
      - d_picom
      - f_kitty_conf
      - d_flashfocus
      - d_dunst
      - f_swal
      - f_scr
      - f_pywal_xresources_template
      - f_post-hibernate
      - f_ls-chars
      - f_lockscreen
      - f_powermenu
      - f_xinitrc
    include:
      - _base
      - rofi

  spaceship:
     include:
       - _base
  atlas:
    include:
      - i3
