config:
  dotpath: dotfiles
  backup: true
  create: true
  banner: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
dotfiles:
  nvim:
    dst: ~/.config/nvim/
    src: config/nvim
    link: link_children
  zathura:
    src: config/zathura
    dst: ~/.config/zathura
    link: link_children
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  pywal_xresources:
    src: Xresources
    dst: ~/.Xresources
  pywal_xresources_template:
    src: config/wal/templates/colors.Xresources
    dst: ~/.Xresources
  d_wallpapers:
    src: wallpapers
    dst: ~/.wallpapers
    link: link_children
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_profile:
    src: profile
    dst: ~/.profile
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
    link: link_children
  d_spicetify:
    src: config/spicetify
    dst: ~/.config/spicetify
    link: link_children
  d_i3:
    src: config/i3
    dst: ~/.config/i3
    link: link_children
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
    link: link_children
  picom:
    src: config/picom
    dst: ~/.config/picom
    link: link_children
  polybar:
    src: config/polybar
    dst: ~/.config/polybar
    link: link_children
  fish_shell:
    src: config/fish
    dst: ~/.config/fish
    link: link_children
  fish_shell_omf:
    src: config/omf
    dst: ~/.config/omf
    link: link_children
  flashfocus:
    src: config/flashfocus
    dst: ~/.config/flashfocus
    link: link_children
  firefox_css:
    src: config/mozilla/firefox/themes
    dst: ~/.config/mozilla/firefox/themes
  firefox_tabpage:
    src: local/bin/run-tabpage
    dst: ~/.local/bin/run-tabpage
  f_deskopen:
    src: local/bin/deskopen
    dst: ~/.local/bin/deskopen
  f_figlet-test:
    src: local/bin/figlet-test
    dst: ~/.local/bin/figlet-test
  rofi_launcher:
    src: local/bin/app-launcher
    dst: ~/.local/bin/app-launcher
  f_launch-singleton:
    src: local/bin/launch-singleton
    dst: ~/.local/bin/launch-singleton
  f_powermenu:
    src: local/bin/powermenu
    dst: ~/.local/bin/powermenu
  f_lockscreen:
    src: local/bin/lockscreen
    dst: ~/.local/bin/lockscreen
  f_ls-chars:
    src: local/bin/ls-chars
    dst: ~/.local/bin/ls-chars
  f_post-hibernate.sh:
    src: local/bin/post-hibernate.sh
    dst: ~/.local/bin/post-hibernate.sh
  f_scr:
    src: local/bin/scr
    dst: ~/.local/bin/scr
  f_swal:
    src: local/bin/swal
    dst: ~/.local/bin/swal
profiles:
  atlas:
    dotfiles:
    - ALL
