#!/usr/bin/env sh

if [ $# = 0 ];
then
    echo "no window class supplied. aborting..."
    exit 1
fi

# kill previous instances
ps aux | grep -P "${BASH_SOURCE[0]} $1\b" \
    | grep -v $$ | grep -P "sh" \
    | awk -F\  '{print $2}' \
    | xargs -I % kill %

WINDOW_CLASS=$1
WINDOW_ID=

xprop -spy -root _NET_ACTIVE_WINDOW \
    | while read -r window
do
    ID="$(echo $window | awk '/_NET_ACTIVE_WINDOW\(WINDOW\)/{ print $NF }')"
    CLASS=$(xprop -id $ID | awk '/WM_CLASS/{$1=$2="";print}' | cut -d'"' -f4)
    if [ ! -z $WINDOW_ID ]; then
        xkill -id $WINDOW_ID
        WINDOW_ID=
    fi
    [ $CLASS = "$WINDOW_CLASS" ] && WINDOW_ID=$ID
done
