#!/usr/bin/env bash


source "${0%/*}/"utils

type n &>/dev/null || curl -L https://git.io/n-install | bash 

[ -x "$N_PREFIX/bin" ] && append_path "$N_PREFIX/bin" \
    && n lts \
    && npm i -g yarn bash-language-server


