#!/bin/sh
#
# wrapper to run around X sessions.

echo "Running X session wrapper" > ~/hmm

c="${XDG_CONFIG_HOME:-$HOME/.config}"

# Launch D-BUS
[ "$DBUS_SESSION_BUS_ADDRESS" ] \
    || exec dbus-launch --exit-with-session "$c/x/initrc" "$@" \
    || exit

# Choose session command
[ "$1" ] || set -- i3
case $1 in
    i3|bspwm|xmonad)
	swp # start sh*tty wallpaper setter
	;;
    kde)     set -- startplasma-x11 ;;
    openbox) set -- openbox --startup "$c/openbox/autostart" ;;
    *)  lch sxhkd picom dunst ;;
esac

# Load profile
for file in "/etc/profile" "$HOME/.profile" "$c/shell/profile" "/etc/xprofile" "$HOME/.xprofile" "$c/x/xprofile" ; do
    if [ -f "$file" ]; then
        echo "Loading profile from $file";
        . "$file"
    fi
done

# Load resources
for file in "/etc/X11/Xresources" "$HOME/.Xresources" "$c/x/resources"; do
    if [ -f "$file" ]; then
        echo "Loading resource: $file"
        xrdb -merge "$file"
    fi
done

echo "X init wrapper complete, running session " "$@" > ~/done
exec "$@"
