#!/usr/bin/env bash
# aset-layout - wait until change of (monitor) outputs, and set custom layout

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

while "$ROOT/xocw"; do
   . "$ROOT"/set-layout
done
