<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version='1.0'>
  <dict>
    <key>name</key>
    <string>i3</string>
    <key>author</key>
    <string>skk</string>
    <key>scopeName</key>
    <string>source.i3</string>
    <key>fileTypes</key>
    <array>
      <string>.i3/config</string>
      <string>i3/config</string>
    </array>
    <key>uuid</key>
    <string>bb9ebd33-1b88-4310-acef-41720bcac38f</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>name</key>
        <string>criteria</string>
        <key>match</key>
        <string>\[(\w+)=(\&quot;.*\&quot;)\]</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>comment</string>
        <key>match</key>
        <string>(\#)(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>comment.line.number-sign.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>comment.line.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>font_pango</string>
        <key>match</key>
        <string>(font\ pango\:)\s*([- ,\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>font</string>
        <key>match</key>
        <string>(font)\s*([-\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>fullscreen</string>
        <key>match</key>
        <string>(fullscreen)\s*(toggle)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>floating_modifier</string>
        <key>match</key>
        <string>(floating_modifier)\s*(\$?\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>floating_minimum_size</string>
        <key>match</key>
        <string>(floating_minimum_size)\s*(-?\d*)\s*(x)\s*(-?\d*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>floating_maximum_size</string>
        <key>match</key>
        <string>(floating_maximum_size)\s*(-?\d*)\s*(x)\s*(-?\d*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>default_orientation</string>
        <key>match</key>
        <string>(default_orientation)\s*(vertical|horizontal|v|h|auto|a)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>workspace_layout</string>
        <key>match</key>
        <string>(workspace_layout)\s*(default|stacking|tabbed|d|s|t)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>new_window_or_float</string>
        <key>match</key>
        <string>(new_(?:window|float))\s*(normal|none|(?:\d*pixel\s\d*))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>hide_edge_borders</string>
        <key>match</key>
        <string>(hide_edge_borders)\s*(vertical|horizontal|none|both|v|h|n|b)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>for_window</string>
        <key>match</key>
        <string>(for_window)\s*\[(\w+)=(\&quot;.*\&quot;)\]\s*</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>set1</string>
        <key>match</key>
        <string>(set)\s*(\$\w*)\s*(\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>set2</string>
        <key>match</key>
        <string>(set)\s*(\$\w*)\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>assign</string>
        <key>match</key>
        <string>(assign)\s*\[(\w+)=(\&quot;.*\&quot;)\]\s*(→)?\s*([\w\d]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>string.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.operator.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>exec_always</string>
        <key>match</key>
        <string>(exec_always)\s*(\-\-no-startup-id)?\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>source.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>exec</string>
        <key>match</key>
        <string>(exec)\s*(\-\-no-startup-id)?\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>source.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_focused1</string>
        <key>match</key>
        <string>(client\.focused)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_focused2</string>
        <key>match</key>
        <string>(client\.focused)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_focused_inactive1</string>
        <key>match</key>
        <string>(client\.focused_inactive)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_focused_inactive2</string>
        <key>match</key>
        <string>(client\.focused_inactive)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_unfocused1</string>
        <key>match</key>
        <string>(client\.unfocused)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_unfocused2</string>
        <key>match</key>
        <string>(client\.unfocused)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_urgent1</string>
        <key>match</key>
        <string>(client\.urgent)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_urgent2</string>
        <key>match</key>
        <string>(client\.urgent)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_placeholder1</string>
        <key>match</key>
        <string>(client\.placeholder)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_placeholder2</string>
        <key>match</key>
        <string>(client\.placeholder)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_background1</string>
        <key>match</key>
        <string>(client\.background)\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>client_background2</string>
        <key>match</key>
        <string>(client\.background)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>ipc_socket</string>
        <key>match</key>
        <string>(ipc-socket)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focus_follows_mouse</string>
        <key>match</key>
        <string>(focus_follows_mouse)\s*(yes|no|y|n)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>popup_during_fullscreen</string>
        <key>match</key>
        <string>(popup_during_fullscreen)\s*(smart|ignore|leave_fullscreen)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>force_focus_wrapping</string>
        <key>match</key>
        <string>(force_focus_wrapping)\s*(yes|no|y|n)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>force_xinerama</string>
        <key>match</key>
        <string>(force_xinerama)\s*(no|yes)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>force_xinerama</string>
        <key>match</key>
        <string>(force_xinerama)\s*(yes|no|y|n)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>workspace_auto_back_and_forth</string>
        <key>match</key>
        <string>(workspace_auto_back_and_forth)\s*(yes|no|y|n)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>force_display_urgency_hint</string>
        <key>match</key>
        <string>(force_display_urgency_hint)\s*(\d*)\s*ms</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bar</string>
        <key>match</key>
        <string>(?:^ *|\G *)(bar)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>i3bar_command</string>
        <key>match</key>
        <string>(i3bar_command)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>status_command</string>
        <key>match</key>
        <string>(status_command)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>modifier</string>
        <key>match</key>
        <string>(modifier)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>hidden_state</string>
        <key>match</key>
        <string>(hidden_state)\s*(show|hide)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>mode</string>
        <key>match</key>
        <string>(mode)\s*(dock|hide|invisible)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>id</string>
        <key>match</key>
        <string>(id)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>position</string>
        <key>match</key>
        <string>(position)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>output</string>
        <key>match</key>
        <string>(output)\s*(\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>tray_output</string>
        <key>match</key>
        <string>(tray_output)\s*(\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>workspace_buttons</string>
        <key>match</key>
        <string>(workspace_buttons)\s*(yes|no|y|n)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>colors</string>
        <key>match</key>
        <string>(colors)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>block.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>background</string>
        <key>match</key>
        <string>(background)\s*([#$\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>statusline1</string>
        <key>match</key>
        <string>(statusline)\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>statusline2</string>
        <key>match</key>
        <string>(statusline)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>separator</string>
        <key>match</key>
        <string>(separator)\s*([#$\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focused_workspace1</string>
        <key>match</key>
        <string>(focused_workspace)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focused_workspace2</string>
        <key>match</key>
        <string>(focused_workspace)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>active_workspace1</string>
        <key>match</key>
        <string>(active_workspace)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>active_workspace2</string>
        <key>match</key>
        <string>(active_workspace)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>inactive_workspace1</string>
        <key>match</key>
        <string>(inactive_workspace)\s*([#\$\w]*)\s*([#\$\w]*)\s*([#\$\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>inactive_workspace2</string>
        <key>match</key>
        <string>(inactive_workspace)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>urgent_workspace1</string>
        <key>match</key>
        <string>(urgent_workspace)\s*(#\w{6})\s*(#\w{6})\s*(#\w{6})</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>urgent_workspace2</string>
        <key>match</key>
        <string>(urgent_workspace)\s*(\$\w*)\s*(\$\w*)\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bindcode</string>
        <key>match</key>
        <string>(bindcode)\s*(--release)?\s*(\d*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bindsym</string>
        <key>match</key>
        <string>(bindsym)\s*(--release)?\s*([$\w\+]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>split</string>
        <key>match</key>
        <string>(split)\s*(vertical|horizontal|v|h)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>layout</string>
        <key>match</key>
        <string>(layout)\s*(default|tabbed|stacking|split v|split h)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>layout_toggle</string>
        <key>match</key>
        <string>(layout toggle)\s*(split|all)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>floating</string>
        <key>match</key>
        <string>(floating)\s*(toggle|enable)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focus</string>
        <key>match</key>
        <string>(focus)\s*(left|right|down|up|l|r|d|u|parent|child|floating|tiling|mode_toggle)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focus_output</string>
        <key>match</key>
        <string>(focus output)\s*(left|right|down|up|l|r|d|u|(?:[-\w]*))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>sticky</string>
        <key>match</key>
        <string>(sticky)\s*(enable)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move</string>
        <key>match</key>
        <string>(move)\s*(left|right|down|up|l|r|d|u)(?:\s*(-?\d*)\s*(px)\s*(?:(-?\d*)\s*(px))?)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move_abs</string>
        <key>match</key>
        <string>(move)\s*(absolute)\s*(position)\s*(?:(\d*)\s*(px))?(?:\s*(\d*)\s*(px))?(?:\s*(center)|\s*(?:(\d*) (px))\s*(?:(\d*)\s*(px)))?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>9</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>10</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>11</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>12</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>workspace</string>
        <key>match</key>
        <string>(workspace)\s*(next|prev|next_on_output|prev_on_output|back_and_forth|(?:\w)*|(?:\d*\s*\w*))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>rename_workspace</string>
        <key>match</key>
        <string>(rename workspace)\s*([:\s\w]*)\s*(to)\s*([:\s\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move__container_or_workspace</string>
        <key>match</key>
        <string>(move)\s*(workspace|container)\s*(to)\s*(output)\s*(left|right|down|up|[\w]*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move_workspace</string>
        <key>match</key>
        <string>(move)\s*(workspace)\s*(next|prev|next_on_output|prev_on_output|back_and_forth|(?:\w)*|(?:\d*\s*\w*))(\$\w*){0,1}</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move__window_or_container1</string>
        <key>match</key>
        <string>(move)\s*(window|container)\s*(to)?\s*(workspace)?\s*(\$\w*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move__window_or_container2</string>
        <key>match</key>
        <string>(move)\s*(window|container)\s*(to)?\s*(workspace)?\s*(\d*)\s*(\$?\w*)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>variable.other.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move__window_or_container3</string>
        <key>match</key>
        <string>(move)\s*(window|container)\s*(to)?\s*(workspace)\s*(prev|next|current)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>resize_mode</string>
        <key>match</key>
        <string>(mode)\s*(\&quot;resize\&quot;)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>resize</string>
        <key>match</key>
        <string>(resize)\s*(grow|shrink)\s*(width|height)\s*(\d*)\s*(px)\s*(or)\s*(\d*)\s*(ppt)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>7</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>8</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>resize_set</string>
        <key>match</key>
        <string>(resize)\s*(set)\s*(\d+)\s*(px)?\s*(\d+)\s*(px)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>4</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>5</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
          <key>6</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>resize_mode_default</string>
        <key>match</key>
        <string>(mode)\s*(\&quot;default\&quot;)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>string.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>focus</string>
        <key>match</key>
        <string>(focus)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>mark_identifier</string>
        <key>match</key>
        <string>(unmark|mark)\s*(.*)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>border</string>
        <key>match</key>
        <string>(border)\s*(none|toggle|(\d+)\s*pixel|(?:pixel|normal)\s*(\d+))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>shmlog</string>
        <key>match</key>
        <string>(shmlog)\s*(?:(on|off|toggle)|(\d*))</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>shmlog</string>
        <key>match</key>
        <string>(debuglog)\s*(on|off|toggle)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>reload</string>
        <key>match</key>
        <string>(reload)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>restart</string>
        <key>match</key>
        <string>(restart)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>exit</string>
        <key>match</key>
        <string>(exit)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>move_scratchpad</string>
        <key>match</key>
        <string>(move)\s*(scratchpad)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>scratchpad_show</string>
        <key>match</key>
        <string>(scratchpad)\s*(show)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bar_hidden_state</string>
        <key>match</key>
        <string>(bar hidden_state)\s*(show|hide|toggle)\s*(.*)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <dict>
        <key>name</key>
        <string>bar_mode</string>
        <key>match</key>
        <string>(mode)\s*(dock|hide|invisible|toggle)\s*(.*)?</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
        </dict>
      </dict>
      <!-- gaps inner <px>
           gaps outer <px> -->
      <dict>
        <key>name</key>
        <string>gaps</string>
        <key>match</key>
        <string>(gaps)\s*(inner|outer)\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
      <!-- gaps inner|outer current|all set|plus|minus <px> -->
      <dict>
        <key>name</key>
        <string>gaps_full</string>
        <key>match</key>
        <string>(gaps)\s*(inner|outer)\s*(current|all)?\s*(set|plus|minus)?\s*(\d+)</string>
        <key>captures</key>
        <dict>
          <key>1</key>
          <dict>
            <key>name</key>
            <string>keyword.control.i3</string>
          </dict>
          <key>2</key>
          <dict>
            <key>name</key>
            <string>constant.language.i3</string>
          </dict>
          <key>3</key>
          <dict>
            <key>name</key>
            <string>constant.numeric.i3</string>
          </dict>
        </dict>
      </dict>
    </array>
  </dict>
</plist>
