begin = "\""
end = "\""
name = "string.quoted.double.html"

[beginCaptures.0]
name = "punctuation.definition.string.begin.html"

[endCaptures.0]
name = "punctuation.definition.string.end.html"

[[patterns]]
include = "#django-stuff"

[[patterns]]
include = "#entities"

