#!/bin/bash

#set colors generated by 'wal'
. "${XDG_CACHE_HOME}/wal/colors.sh"

dunst \
-frame_width 0 \
    -lb "${color0}" \
    -nb "${color0}" \
    -cb "${color0}" \
    -bf "${color7}" \
    -cf "${color7}" \
    -nf "${color7}"
