#!/bin/bash

fish -c "type -q omf" || curl -L https://get.oh-my.fish | fish
fish -c "omf install https://github.com/folws/ortega && omf theme ortega"

if prompt "Would you like to set fish as your default prompt?" y ; then
  chsh -s $(command -v fish)
fi
